// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sentinel/subscription/v3/events.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Sentinel_Subscription_V3_EventAllocate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var accAddress: String = String()

  var grantedBytes: String = String()

  var utilisedBytes: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventCreate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var price: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventCreateSession: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sessionID: UInt64 = 0

  var subscriptionID: UInt64 = 0

  var accAddress: String = String()

  var nodeAddress: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventEnd: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventPay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var provAddress: String = String()

  var payment: String = String()

  var stakingReward: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventRenew: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var price: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventUpdateDetails: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var renewalPricePolicy: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sentinel_Subscription_V3_EventUpdateStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subscriptionID: UInt64 = 0

  var planID: UInt64 = 0

  var accAddress: String = String()

  var status: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sentinel.subscription.v3"

extension Sentinel_Subscription_V3_EventAllocate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventAllocate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}acc_address\0\u{3}granted_bytes\0\u{3}utilised_bytes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.grantedBytes) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.utilisedBytes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 2)
    }
    if !self.grantedBytes.isEmpty {
      try visitor.visitSingularStringField(value: self.grantedBytes, fieldNumber: 3)
    }
    if !self.utilisedBytes.isEmpty {
      try visitor.visitSingularStringField(value: self.utilisedBytes, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventAllocate, rhs: Sentinel_Subscription_V3_EventAllocate) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.grantedBytes != rhs.grantedBytes {return false}
    if lhs.utilisedBytes != rhs.utilisedBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventCreate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventCreate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0\u{1}price\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.price) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    if !self.price.isEmpty {
      try visitor.visitSingularStringField(value: self.price, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventCreate, rhs: Sentinel_Subscription_V3_EventCreate) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.price != rhs.price {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventCreateSession: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventCreateSession"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}acc_address\0\u{3}node_address\0\u{3}subscription_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.nodeAddress) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sessionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.sessionID, fieldNumber: 1)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 2)
    }
    if !self.nodeAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.nodeAddress, fieldNumber: 3)
    }
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventCreateSession, rhs: Sentinel_Subscription_V3_EventCreateSession) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.nodeAddress != rhs.nodeAddress {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventEnd: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventEnd"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventEnd, rhs: Sentinel_Subscription_V3_EventEnd) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventPay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventPay"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0\u{3}prov_address\0\u{1}payment\0\u{3}staking_reward\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.provAddress) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.payment) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.stakingReward) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    if !self.provAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.provAddress, fieldNumber: 4)
    }
    if !self.payment.isEmpty {
      try visitor.visitSingularStringField(value: self.payment, fieldNumber: 5)
    }
    if !self.stakingReward.isEmpty {
      try visitor.visitSingularStringField(value: self.stakingReward, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventPay, rhs: Sentinel_Subscription_V3_EventPay) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.provAddress != rhs.provAddress {return false}
    if lhs.payment != rhs.payment {return false}
    if lhs.stakingReward != rhs.stakingReward {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventRenew: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventRenew"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0\u{1}price\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.price) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    if !self.price.isEmpty {
      try visitor.visitSingularStringField(value: self.price, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventRenew, rhs: Sentinel_Subscription_V3_EventRenew) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.price != rhs.price {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventUpdateDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventUpdateDetails"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0\u{3}renewal_price_policy\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.renewalPricePolicy) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    if !self.renewalPricePolicy.isEmpty {
      try visitor.visitSingularStringField(value: self.renewalPricePolicy, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventUpdateDetails, rhs: Sentinel_Subscription_V3_EventUpdateDetails) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.renewalPricePolicy != rhs.renewalPricePolicy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sentinel_Subscription_V3_EventUpdateStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EventUpdateStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}subscription_id\0\u{3}plan_id\0\u{3}acc_address\0\u{1}status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.planID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.subscriptionID != 0 {
      try visitor.visitSingularUInt64Field(value: self.subscriptionID, fieldNumber: 1)
    }
    if self.planID != 0 {
      try visitor.visitSingularUInt64Field(value: self.planID, fieldNumber: 2)
    }
    if !self.accAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.accAddress, fieldNumber: 3)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Subscription_V3_EventUpdateStatus, rhs: Sentinel_Subscription_V3_EventUpdateStatus) -> Bool {
    if lhs.subscriptionID != rhs.subscriptionID {return false}
    if lhs.planID != rhs.planID {return false}
    if lhs.accAddress != rhs.accAddress {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
