//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/provider/v3/msg.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Provider_V3_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Provider_V3_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgRegisterProvider(
    _ request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse>

  func msgUpdateProviderDetails(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>

  func msgUpdateProviderStatus(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>

  func msgUpdateParams(
    _ request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse>
}

extension Sentinel_Provider_V3_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.provider.v3.MsgService"
  }

  /// Unary call to MsgRegisterProvider
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgRegisterProvider.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgRegisterProvider(
    _ request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgRegisterProvider.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterProviderInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateProviderDetails
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateProviderDetails.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateProviderDetails(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderDetails.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderDetailsInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateProviderStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateProviderStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateProviderStatus(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderStatusInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateParams
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateParams(
    _ request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Provider_V3_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Provider_V3_MsgServiceNIOClient")
internal final class Sentinel_Provider_V3_MsgServiceClient: Sentinel_Provider_V3_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.provider.v3.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Provider_V3_MsgServiceNIOClient: Sentinel_Provider_V3_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.provider.v3.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Provider_V3_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgRegisterProviderCall(
    _ request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse>

  func makeMsgUpdateProviderDetailsCall(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>

  func makeMsgUpdateProviderStatusCall(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>

  func makeMsgUpdateParamsCall(
    _ request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V3_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Provider_V3_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgRegisterProviderCall(
    _ request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgRegisterProvider.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterProviderInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateProviderDetailsCall(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderDetails.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderDetailsInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateProviderStatusCall(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderStatusInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateParamsCall(
    _ request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V3_MsgServiceAsyncClientProtocol {
  internal func msgRegisterProvider(
    _ request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V3_MsgRegisterProviderResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgRegisterProvider.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterProviderInterceptors() ?? []
    )
  }

  internal func msgUpdateProviderDetails(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderDetails.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderDetailsInterceptors() ?? []
    )
  }

  internal func msgUpdateProviderStatus(
    _ request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V3_MsgUpdateProviderStatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateProviderStatusInterceptors() ?? []
    )
  }

  internal func msgUpdateParams(
    _ request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V3_MsgUpdateParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Provider_V3_MsgServiceAsyncClient: Sentinel_Provider_V3_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Provider_V3_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgRegisterProvider'.
  func makeMsgRegisterProviderInterceptors() -> [ClientInterceptor<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateProviderDetails'.
  func makeMsgUpdateProviderDetailsInterceptors() -> [ClientInterceptor<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateProviderStatus'.
  func makeMsgUpdateProviderStatusInterceptors() -> [ClientInterceptor<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateParams'.
  func makeMsgUpdateParamsInterceptors() -> [ClientInterceptor<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse>]
}

internal enum Sentinel_Provider_V3_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.provider.v3.MsgService",
    methods: [
      Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgRegisterProvider,
      Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderDetails,
      Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateProviderStatus,
      Sentinel_Provider_V3_MsgServiceClientMetadata.Methods.msgUpdateParams,
    ]
  )

  internal enum Methods {
    internal static let msgRegisterProvider = GRPCMethodDescriptor(
      name: "MsgRegisterProvider",
      path: "/sentinel.provider.v3.MsgService/MsgRegisterProvider",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateProviderDetails = GRPCMethodDescriptor(
      name: "MsgUpdateProviderDetails",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateProviderDetails",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateProviderStatus = GRPCMethodDescriptor(
      name: "MsgUpdateProviderStatus",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateProviderStatus",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateParams = GRPCMethodDescriptor(
      name: "MsgUpdateParams",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateParams",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Provider_V3_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Provider_V3_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgRegisterProvider(request: Sentinel_Provider_V3_MsgRegisterProviderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V3_MsgRegisterProviderResponse>

  func msgUpdateProviderDetails(request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>

  func msgUpdateProviderStatus(request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>

  func msgUpdateParams(request: Sentinel_Provider_V3_MsgUpdateParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V3_MsgUpdateParamsResponse>
}

extension Sentinel_Provider_V3_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Provider_V3_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgRegisterProvider":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgRegisterProviderRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgRegisterProviderResponse>(),
        interceptors: self.interceptors?.makeMsgRegisterProviderInterceptors() ?? [],
        userFunction: self.msgRegisterProvider(request:context:)
      )

    case "MsgUpdateProviderDetails":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateProviderDetailsInterceptors() ?? [],
        userFunction: self.msgUpdateProviderDetails(request:context:)
      )

    case "MsgUpdateProviderStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateProviderStatusInterceptors() ?? [],
        userFunction: self.msgUpdateProviderStatus(request:context:)
      )

    case "MsgUpdateParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateParamsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? [],
        userFunction: self.msgUpdateParams(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Provider_V3_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Provider_V3_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgRegisterProvider(
    request: Sentinel_Provider_V3_MsgRegisterProviderRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V3_MsgRegisterProviderResponse

  func msgUpdateProviderDetails(
    request: Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse

  func msgUpdateProviderStatus(
    request: Sentinel_Provider_V3_MsgUpdateProviderStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V3_MsgUpdateProviderStatusResponse

  func msgUpdateParams(
    request: Sentinel_Provider_V3_MsgUpdateParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V3_MsgUpdateParamsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V3_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Provider_V3_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Provider_V3_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Provider_V3_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgRegisterProvider":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgRegisterProviderRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgRegisterProviderResponse>(),
        interceptors: self.interceptors?.makeMsgRegisterProviderInterceptors() ?? [],
        wrapping: { try await self.msgRegisterProvider(request: $0, context: $1) }
      )

    case "MsgUpdateProviderDetails":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateProviderDetailsInterceptors() ?? [],
        wrapping: { try await self.msgUpdateProviderDetails(request: $0, context: $1) }
      )

    case "MsgUpdateProviderStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateProviderStatusInterceptors() ?? [],
        wrapping: { try await self.msgUpdateProviderStatus(request: $0, context: $1) }
      )

    case "MsgUpdateParams":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V3_MsgUpdateParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V3_MsgUpdateParamsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? [],
        wrapping: { try await self.msgUpdateParams(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Provider_V3_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgRegisterProvider'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgRegisterProviderInterceptors() -> [ServerInterceptor<Sentinel_Provider_V3_MsgRegisterProviderRequest, Sentinel_Provider_V3_MsgRegisterProviderResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateProviderDetails'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateProviderDetailsInterceptors() -> [ServerInterceptor<Sentinel_Provider_V3_MsgUpdateProviderDetailsRequest, Sentinel_Provider_V3_MsgUpdateProviderDetailsResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateProviderStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateProviderStatusInterceptors() -> [ServerInterceptor<Sentinel_Provider_V3_MsgUpdateProviderStatusRequest, Sentinel_Provider_V3_MsgUpdateProviderStatusResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateParamsInterceptors() -> [ServerInterceptor<Sentinel_Provider_V3_MsgUpdateParamsRequest, Sentinel_Provider_V3_MsgUpdateParamsResponse>]
}

internal enum Sentinel_Provider_V3_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.provider.v3.MsgService",
    methods: [
      Sentinel_Provider_V3_MsgServiceServerMetadata.Methods.msgRegisterProvider,
      Sentinel_Provider_V3_MsgServiceServerMetadata.Methods.msgUpdateProviderDetails,
      Sentinel_Provider_V3_MsgServiceServerMetadata.Methods.msgUpdateProviderStatus,
      Sentinel_Provider_V3_MsgServiceServerMetadata.Methods.msgUpdateParams,
    ]
  )

  internal enum Methods {
    internal static let msgRegisterProvider = GRPCMethodDescriptor(
      name: "MsgRegisterProvider",
      path: "/sentinel.provider.v3.MsgService/MsgRegisterProvider",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateProviderDetails = GRPCMethodDescriptor(
      name: "MsgUpdateProviderDetails",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateProviderDetails",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateProviderStatus = GRPCMethodDescriptor(
      name: "MsgUpdateProviderStatus",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateProviderStatus",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateParams = GRPCMethodDescriptor(
      name: "MsgUpdateParams",
      path: "/sentinel.provider.v3.MsgService/MsgUpdateParams",
      type: GRPCCallType.unary
    )
  }
}
