//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/provider/v2/msg.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Provider_V2_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Provider_V2_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgRegister(
    _ request: Sentinel_Provider_V2_MsgRegisterRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse>

  func msgUpdate(
    _ request: Sentinel_Provider_V2_MsgUpdateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse>
}

extension Sentinel_Provider_V2_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.provider.v2.MsgService"
  }

  /// Unary call to MsgRegister
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgRegister.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgRegister(
    _ request: Sentinel_Provider_V2_MsgRegisterRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgRegister.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdate
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdate.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdate(
    _ request: Sentinel_Provider_V2_MsgUpdateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgUpdate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Provider_V2_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Provider_V2_MsgServiceNIOClient")
internal final class Sentinel_Provider_V2_MsgServiceClient: Sentinel_Provider_V2_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.provider.v2.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Provider_V2_MsgServiceNIOClient: Sentinel_Provider_V2_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.provider.v2.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Provider_V2_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgRegisterCall(
    _ request: Sentinel_Provider_V2_MsgRegisterRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse>

  func makeMsgUpdateCall(
    _ request: Sentinel_Provider_V2_MsgUpdateRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V2_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Provider_V2_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgRegisterCall(
    _ request: Sentinel_Provider_V2_MsgRegisterRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgRegister.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateCall(
    _ request: Sentinel_Provider_V2_MsgUpdateRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgUpdate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V2_MsgServiceAsyncClientProtocol {
  internal func msgRegister(
    _ request: Sentinel_Provider_V2_MsgRegisterRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V2_MsgRegisterResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgRegister.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRegisterInterceptors() ?? []
    )
  }

  internal func msgUpdate(
    _ request: Sentinel_Provider_V2_MsgUpdateRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Provider_V2_MsgUpdateResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgUpdate.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Provider_V2_MsgServiceAsyncClient: Sentinel_Provider_V2_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Provider_V2_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgRegister'.
  func makeMsgRegisterInterceptors() -> [ClientInterceptor<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdate'.
  func makeMsgUpdateInterceptors() -> [ClientInterceptor<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse>]
}

internal enum Sentinel_Provider_V2_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.provider.v2.MsgService",
    methods: [
      Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgRegister,
      Sentinel_Provider_V2_MsgServiceClientMetadata.Methods.msgUpdate,
    ]
  )

  internal enum Methods {
    internal static let msgRegister = GRPCMethodDescriptor(
      name: "MsgRegister",
      path: "/sentinel.provider.v2.MsgService/MsgRegister",
      type: GRPCCallType.unary
    )

    internal static let msgUpdate = GRPCMethodDescriptor(
      name: "MsgUpdate",
      path: "/sentinel.provider.v2.MsgService/MsgUpdate",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Provider_V2_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Provider_V2_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgRegister(request: Sentinel_Provider_V2_MsgRegisterRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V2_MsgRegisterResponse>

  func msgUpdate(request: Sentinel_Provider_V2_MsgUpdateRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Provider_V2_MsgUpdateResponse>
}

extension Sentinel_Provider_V2_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Provider_V2_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgRegister":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V2_MsgRegisterRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V2_MsgRegisterResponse>(),
        interceptors: self.interceptors?.makeMsgRegisterInterceptors() ?? [],
        userFunction: self.msgRegister(request:context:)
      )

    case "MsgUpdate":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V2_MsgUpdateRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V2_MsgUpdateResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateInterceptors() ?? [],
        userFunction: self.msgUpdate(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Provider_V2_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Provider_V2_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgRegister(
    request: Sentinel_Provider_V2_MsgRegisterRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V2_MsgRegisterResponse

  func msgUpdate(
    request: Sentinel_Provider_V2_MsgUpdateRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Provider_V2_MsgUpdateResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Provider_V2_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Provider_V2_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Provider_V2_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Provider_V2_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgRegister":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V2_MsgRegisterRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V2_MsgRegisterResponse>(),
        interceptors: self.interceptors?.makeMsgRegisterInterceptors() ?? [],
        wrapping: { try await self.msgRegister(request: $0, context: $1) }
      )

    case "MsgUpdate":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Provider_V2_MsgUpdateRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Provider_V2_MsgUpdateResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateInterceptors() ?? [],
        wrapping: { try await self.msgUpdate(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Provider_V2_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgRegister'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgRegisterInterceptors() -> [ServerInterceptor<Sentinel_Provider_V2_MsgRegisterRequest, Sentinel_Provider_V2_MsgRegisterResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdate'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateInterceptors() -> [ServerInterceptor<Sentinel_Provider_V2_MsgUpdateRequest, Sentinel_Provider_V2_MsgUpdateResponse>]
}

internal enum Sentinel_Provider_V2_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.provider.v2.MsgService",
    methods: [
      Sentinel_Provider_V2_MsgServiceServerMetadata.Methods.msgRegister,
      Sentinel_Provider_V2_MsgServiceServerMetadata.Methods.msgUpdate,
    ]
  )

  internal enum Methods {
    internal static let msgRegister = GRPCMethodDescriptor(
      name: "MsgRegister",
      path: "/sentinel.provider.v2.MsgService/MsgRegister",
      type: GRPCCallType.unary
    )

    internal static let msgUpdate = GRPCMethodDescriptor(
      name: "MsgUpdate",
      path: "/sentinel.provider.v2.MsgService/MsgUpdate",
      type: GRPCCallType.unary
    )
  }
}
