//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/plan/v1/msg.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Plan_V1_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Plan_V1_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgAdd(
    _ request: Sentinel_Plan_V1_MsgAddRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse>

  func msgAddNode(
    _ request: Sentinel_Plan_V1_MsgAddNodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse>

  func msgRemoveNode(
    _ request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse>

  func msgSetStatus(
    _ request: Sentinel_Plan_V1_MsgSetStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse>
}

extension Sentinel_Plan_V1_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.plan.v1.MsgService"
  }

  /// Unary call to MsgAdd
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgAdd.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgAdd(
    _ request: Sentinel_Plan_V1_MsgAddRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAdd.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddInterceptors() ?? []
    )
  }

  /// Unary call to MsgAddNode
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgAddNode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgAddNode(
    _ request: Sentinel_Plan_V1_MsgAddNodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAddNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddNodeInterceptors() ?? []
    )
  }

  /// Unary call to MsgRemoveNode
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgRemoveNode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgRemoveNode(
    _ request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgRemoveNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRemoveNodeInterceptors() ?? []
    )
  }

  /// Unary call to MsgSetStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgSetStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgSetStatus(
    _ request: Sentinel_Plan_V1_MsgSetStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgSetStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSetStatusInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Plan_V1_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Plan_V1_MsgServiceNIOClient")
internal final class Sentinel_Plan_V1_MsgServiceClient: Sentinel_Plan_V1_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.plan.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Plan_V1_MsgServiceNIOClient: Sentinel_Plan_V1_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.plan.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Plan_V1_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgAddCall(
    _ request: Sentinel_Plan_V1_MsgAddRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse>

  func makeMsgAddNodeCall(
    _ request: Sentinel_Plan_V1_MsgAddNodeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse>

  func makeMsgRemoveNodeCall(
    _ request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse>

  func makeMsgSetStatusCall(
    _ request: Sentinel_Plan_V1_MsgSetStatusRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Plan_V1_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Plan_V1_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgAddCall(
    _ request: Sentinel_Plan_V1_MsgAddRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAdd.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddInterceptors() ?? []
    )
  }

  internal func makeMsgAddNodeCall(
    _ request: Sentinel_Plan_V1_MsgAddNodeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAddNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddNodeInterceptors() ?? []
    )
  }

  internal func makeMsgRemoveNodeCall(
    _ request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgRemoveNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRemoveNodeInterceptors() ?? []
    )
  }

  internal func makeMsgSetStatusCall(
    _ request: Sentinel_Plan_V1_MsgSetStatusRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgSetStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSetStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Plan_V1_MsgServiceAsyncClientProtocol {
  internal func msgAdd(
    _ request: Sentinel_Plan_V1_MsgAddRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Plan_V1_MsgAddResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAdd.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddInterceptors() ?? []
    )
  }

  internal func msgAddNode(
    _ request: Sentinel_Plan_V1_MsgAddNodeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Plan_V1_MsgAddNodeResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAddNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddNodeInterceptors() ?? []
    )
  }

  internal func msgRemoveNode(
    _ request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Plan_V1_MsgRemoveNodeResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgRemoveNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgRemoveNodeInterceptors() ?? []
    )
  }

  internal func msgSetStatus(
    _ request: Sentinel_Plan_V1_MsgSetStatusRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Plan_V1_MsgSetStatusResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgSetStatus.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSetStatusInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Plan_V1_MsgServiceAsyncClient: Sentinel_Plan_V1_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Plan_V1_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgAdd'.
  func makeMsgAddInterceptors() -> [ClientInterceptor<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse>]

  /// - Returns: Interceptors to use when invoking 'msgAddNode'.
  func makeMsgAddNodeInterceptors() -> [ClientInterceptor<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse>]

  /// - Returns: Interceptors to use when invoking 'msgRemoveNode'.
  func makeMsgRemoveNodeInterceptors() -> [ClientInterceptor<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse>]

  /// - Returns: Interceptors to use when invoking 'msgSetStatus'.
  func makeMsgSetStatusInterceptors() -> [ClientInterceptor<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse>]
}

internal enum Sentinel_Plan_V1_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.plan.v1.MsgService",
    methods: [
      Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAdd,
      Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgAddNode,
      Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgRemoveNode,
      Sentinel_Plan_V1_MsgServiceClientMetadata.Methods.msgSetStatus,
    ]
  )

  internal enum Methods {
    internal static let msgAdd = GRPCMethodDescriptor(
      name: "MsgAdd",
      path: "/sentinel.plan.v1.MsgService/MsgAdd",
      type: GRPCCallType.unary
    )

    internal static let msgAddNode = GRPCMethodDescriptor(
      name: "MsgAddNode",
      path: "/sentinel.plan.v1.MsgService/MsgAddNode",
      type: GRPCCallType.unary
    )

    internal static let msgRemoveNode = GRPCMethodDescriptor(
      name: "MsgRemoveNode",
      path: "/sentinel.plan.v1.MsgService/MsgRemoveNode",
      type: GRPCCallType.unary
    )

    internal static let msgSetStatus = GRPCMethodDescriptor(
      name: "MsgSetStatus",
      path: "/sentinel.plan.v1.MsgService/MsgSetStatus",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Plan_V1_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Plan_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgAdd(request: Sentinel_Plan_V1_MsgAddRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Plan_V1_MsgAddResponse>

  func msgAddNode(request: Sentinel_Plan_V1_MsgAddNodeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Plan_V1_MsgAddNodeResponse>

  func msgRemoveNode(request: Sentinel_Plan_V1_MsgRemoveNodeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Plan_V1_MsgRemoveNodeResponse>

  func msgSetStatus(request: Sentinel_Plan_V1_MsgSetStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Plan_V1_MsgSetStatusResponse>
}

extension Sentinel_Plan_V1_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Plan_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgAdd":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgAddRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgAddResponse>(),
        interceptors: self.interceptors?.makeMsgAddInterceptors() ?? [],
        userFunction: self.msgAdd(request:context:)
      )

    case "MsgAddNode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgAddNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgAddNodeResponse>(),
        interceptors: self.interceptors?.makeMsgAddNodeInterceptors() ?? [],
        userFunction: self.msgAddNode(request:context:)
      )

    case "MsgRemoveNode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgRemoveNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgRemoveNodeResponse>(),
        interceptors: self.interceptors?.makeMsgRemoveNodeInterceptors() ?? [],
        userFunction: self.msgRemoveNode(request:context:)
      )

    case "MsgSetStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgSetStatusRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgSetStatusResponse>(),
        interceptors: self.interceptors?.makeMsgSetStatusInterceptors() ?? [],
        userFunction: self.msgSetStatus(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Plan_V1_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Plan_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgAdd(
    request: Sentinel_Plan_V1_MsgAddRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Plan_V1_MsgAddResponse

  func msgAddNode(
    request: Sentinel_Plan_V1_MsgAddNodeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Plan_V1_MsgAddNodeResponse

  func msgRemoveNode(
    request: Sentinel_Plan_V1_MsgRemoveNodeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Plan_V1_MsgRemoveNodeResponse

  func msgSetStatus(
    request: Sentinel_Plan_V1_MsgSetStatusRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Plan_V1_MsgSetStatusResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Plan_V1_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Plan_V1_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Plan_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Plan_V1_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgAdd":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgAddRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgAddResponse>(),
        interceptors: self.interceptors?.makeMsgAddInterceptors() ?? [],
        wrapping: { try await self.msgAdd(request: $0, context: $1) }
      )

    case "MsgAddNode":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgAddNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgAddNodeResponse>(),
        interceptors: self.interceptors?.makeMsgAddNodeInterceptors() ?? [],
        wrapping: { try await self.msgAddNode(request: $0, context: $1) }
      )

    case "MsgRemoveNode":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgRemoveNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgRemoveNodeResponse>(),
        interceptors: self.interceptors?.makeMsgRemoveNodeInterceptors() ?? [],
        wrapping: { try await self.msgRemoveNode(request: $0, context: $1) }
      )

    case "MsgSetStatus":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Plan_V1_MsgSetStatusRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Plan_V1_MsgSetStatusResponse>(),
        interceptors: self.interceptors?.makeMsgSetStatusInterceptors() ?? [],
        wrapping: { try await self.msgSetStatus(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Plan_V1_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgAdd'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgAddInterceptors() -> [ServerInterceptor<Sentinel_Plan_V1_MsgAddRequest, Sentinel_Plan_V1_MsgAddResponse>]

  /// - Returns: Interceptors to use when handling 'msgAddNode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgAddNodeInterceptors() -> [ServerInterceptor<Sentinel_Plan_V1_MsgAddNodeRequest, Sentinel_Plan_V1_MsgAddNodeResponse>]

  /// - Returns: Interceptors to use when handling 'msgRemoveNode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgRemoveNodeInterceptors() -> [ServerInterceptor<Sentinel_Plan_V1_MsgRemoveNodeRequest, Sentinel_Plan_V1_MsgRemoveNodeResponse>]

  /// - Returns: Interceptors to use when handling 'msgSetStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgSetStatusInterceptors() -> [ServerInterceptor<Sentinel_Plan_V1_MsgSetStatusRequest, Sentinel_Plan_V1_MsgSetStatusResponse>]
}

internal enum Sentinel_Plan_V1_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.plan.v1.MsgService",
    methods: [
      Sentinel_Plan_V1_MsgServiceServerMetadata.Methods.msgAdd,
      Sentinel_Plan_V1_MsgServiceServerMetadata.Methods.msgAddNode,
      Sentinel_Plan_V1_MsgServiceServerMetadata.Methods.msgRemoveNode,
      Sentinel_Plan_V1_MsgServiceServerMetadata.Methods.msgSetStatus,
    ]
  )

  internal enum Methods {
    internal static let msgAdd = GRPCMethodDescriptor(
      name: "MsgAdd",
      path: "/sentinel.plan.v1.MsgService/MsgAdd",
      type: GRPCCallType.unary
    )

    internal static let msgAddNode = GRPCMethodDescriptor(
      name: "MsgAddNode",
      path: "/sentinel.plan.v1.MsgService/MsgAddNode",
      type: GRPCCallType.unary
    )

    internal static let msgRemoveNode = GRPCMethodDescriptor(
      name: "MsgRemoveNode",
      path: "/sentinel.plan.v1.MsgService/MsgRemoveNode",
      type: GRPCCallType.unary
    )

    internal static let msgSetStatus = GRPCMethodDescriptor(
      name: "MsgSetStatus",
      path: "/sentinel.plan.v1.MsgService/MsgSetStatus",
      type: GRPCCallType.unary
    )
  }
}
