// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sentinel/session/v3/params.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Sentinel_Session_V3_Params: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var maxGigabytes: Int64 = 0

  var minGigabytes: Int64 = 0

  var maxHours: Int64 = 0

  var minHours: Int64 = 0

  var proofVerificationEnabled: Bool = false

  var stakingShare: String = String()

  var statusTimeout: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _statusTimeout ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_statusTimeout = newValue}
  }
  /// Returns true if `statusTimeout` has been explicitly set.
  var hasStatusTimeout: Bool {return self._statusTimeout != nil}
  /// Clears the value of `statusTimeout`. Subsequent reads from it will return its default value.
  mutating func clearStatusTimeout() {self._statusTimeout = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _statusTimeout: SwiftProtobuf.Google_Protobuf_Duration? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sentinel.session.v3"

extension Sentinel_Session_V3_Params: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Params"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}max_gigabytes\0\u{3}min_gigabytes\0\u{3}max_hours\0\u{3}min_hours\0\u{3}proof_verification_enabled\0\u{3}staking_share\0\u{3}status_timeout\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.maxGigabytes) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.minGigabytes) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.maxHours) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.minHours) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.proofVerificationEnabled) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.stakingShare) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._statusTimeout) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.maxGigabytes != 0 {
      try visitor.visitSingularInt64Field(value: self.maxGigabytes, fieldNumber: 1)
    }
    if self.minGigabytes != 0 {
      try visitor.visitSingularInt64Field(value: self.minGigabytes, fieldNumber: 2)
    }
    if self.maxHours != 0 {
      try visitor.visitSingularInt64Field(value: self.maxHours, fieldNumber: 3)
    }
    if self.minHours != 0 {
      try visitor.visitSingularInt64Field(value: self.minHours, fieldNumber: 4)
    }
    if self.proofVerificationEnabled != false {
      try visitor.visitSingularBoolField(value: self.proofVerificationEnabled, fieldNumber: 5)
    }
    if !self.stakingShare.isEmpty {
      try visitor.visitSingularStringField(value: self.stakingShare, fieldNumber: 6)
    }
    try { if let v = self._statusTimeout {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sentinel_Session_V3_Params, rhs: Sentinel_Session_V3_Params) -> Bool {
    if lhs.maxGigabytes != rhs.maxGigabytes {return false}
    if lhs.minGigabytes != rhs.minGigabytes {return false}
    if lhs.maxHours != rhs.maxHours {return false}
    if lhs.minHours != rhs.minHours {return false}
    if lhs.proofVerificationEnabled != rhs.proofVerificationEnabled {return false}
    if lhs.stakingShare != rhs.stakingShare {return false}
    if lhs._statusTimeout != rhs._statusTimeout {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
