//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/session/v3/msg.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Session_V3_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Session_V3_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgCancelSession(
    _ request: Sentinel_Session_V3_MsgCancelSessionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse>

  func msgUpdateSession(
    _ request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse>

  func msgUpdateParams(
    _ request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse>
}

extension Sentinel_Session_V3_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.session.v3.MsgService"
  }

  /// Unary call to MsgCancelSession
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgCancelSession.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgCancelSession(
    _ request: Sentinel_Session_V3_MsgCancelSessionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgCancelSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelSessionInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateSession
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateSession.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateSession(
    _ request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateSessionInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateParams
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateParams(
    _ request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Session_V3_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Session_V3_MsgServiceNIOClient")
internal final class Sentinel_Session_V3_MsgServiceClient: Sentinel_Session_V3_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.session.v3.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Session_V3_MsgServiceNIOClient: Sentinel_Session_V3_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.session.v3.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Session_V3_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgCancelSessionCall(
    _ request: Sentinel_Session_V3_MsgCancelSessionRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse>

  func makeMsgUpdateSessionCall(
    _ request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse>

  func makeMsgUpdateParamsCall(
    _ request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Session_V3_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Session_V3_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgCancelSessionCall(
    _ request: Sentinel_Session_V3_MsgCancelSessionRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgCancelSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelSessionInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateSessionCall(
    _ request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateSessionInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateParamsCall(
    _ request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Session_V3_MsgServiceAsyncClientProtocol {
  internal func msgCancelSession(
    _ request: Sentinel_Session_V3_MsgCancelSessionRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Session_V3_MsgCancelSessionResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgCancelSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelSessionInterceptors() ?? []
    )
  }

  internal func msgUpdateSession(
    _ request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Session_V3_MsgUpdateSessionResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateSession.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateSessionInterceptors() ?? []
    )
  }

  internal func msgUpdateParams(
    _ request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Session_V3_MsgUpdateParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Session_V3_MsgServiceAsyncClient: Sentinel_Session_V3_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Session_V3_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgCancelSession'.
  func makeMsgCancelSessionInterceptors() -> [ClientInterceptor<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateSession'.
  func makeMsgUpdateSessionInterceptors() -> [ClientInterceptor<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateParams'.
  func makeMsgUpdateParamsInterceptors() -> [ClientInterceptor<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse>]
}

internal enum Sentinel_Session_V3_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.session.v3.MsgService",
    methods: [
      Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgCancelSession,
      Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateSession,
      Sentinel_Session_V3_MsgServiceClientMetadata.Methods.msgUpdateParams,
    ]
  )

  internal enum Methods {
    internal static let msgCancelSession = GRPCMethodDescriptor(
      name: "MsgCancelSession",
      path: "/sentinel.session.v3.MsgService/MsgCancelSession",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateSession = GRPCMethodDescriptor(
      name: "MsgUpdateSession",
      path: "/sentinel.session.v3.MsgService/MsgUpdateSession",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateParams = GRPCMethodDescriptor(
      name: "MsgUpdateParams",
      path: "/sentinel.session.v3.MsgService/MsgUpdateParams",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Session_V3_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Session_V3_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgCancelSession(request: Sentinel_Session_V3_MsgCancelSessionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Session_V3_MsgCancelSessionResponse>

  func msgUpdateSession(request: Sentinel_Session_V3_MsgUpdateSessionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Session_V3_MsgUpdateSessionResponse>

  func msgUpdateParams(request: Sentinel_Session_V3_MsgUpdateParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Session_V3_MsgUpdateParamsResponse>
}

extension Sentinel_Session_V3_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Session_V3_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgCancelSession":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgCancelSessionRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgCancelSessionResponse>(),
        interceptors: self.interceptors?.makeMsgCancelSessionInterceptors() ?? [],
        userFunction: self.msgCancelSession(request:context:)
      )

    case "MsgUpdateSession":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgUpdateSessionRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgUpdateSessionResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateSessionInterceptors() ?? [],
        userFunction: self.msgUpdateSession(request:context:)
      )

    case "MsgUpdateParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgUpdateParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgUpdateParamsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? [],
        userFunction: self.msgUpdateParams(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Session_V3_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Session_V3_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgCancelSession(
    request: Sentinel_Session_V3_MsgCancelSessionRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Session_V3_MsgCancelSessionResponse

  func msgUpdateSession(
    request: Sentinel_Session_V3_MsgUpdateSessionRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Session_V3_MsgUpdateSessionResponse

  func msgUpdateParams(
    request: Sentinel_Session_V3_MsgUpdateParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Session_V3_MsgUpdateParamsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Session_V3_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Session_V3_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Session_V3_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Session_V3_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgCancelSession":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgCancelSessionRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgCancelSessionResponse>(),
        interceptors: self.interceptors?.makeMsgCancelSessionInterceptors() ?? [],
        wrapping: { try await self.msgCancelSession(request: $0, context: $1) }
      )

    case "MsgUpdateSession":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgUpdateSessionRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgUpdateSessionResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateSessionInterceptors() ?? [],
        wrapping: { try await self.msgUpdateSession(request: $0, context: $1) }
      )

    case "MsgUpdateParams":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Session_V3_MsgUpdateParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Session_V3_MsgUpdateParamsResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateParamsInterceptors() ?? [],
        wrapping: { try await self.msgUpdateParams(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Session_V3_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgCancelSession'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgCancelSessionInterceptors() -> [ServerInterceptor<Sentinel_Session_V3_MsgCancelSessionRequest, Sentinel_Session_V3_MsgCancelSessionResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateSession'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateSessionInterceptors() -> [ServerInterceptor<Sentinel_Session_V3_MsgUpdateSessionRequest, Sentinel_Session_V3_MsgUpdateSessionResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateParamsInterceptors() -> [ServerInterceptor<Sentinel_Session_V3_MsgUpdateParamsRequest, Sentinel_Session_V3_MsgUpdateParamsResponse>]
}

internal enum Sentinel_Session_V3_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.session.v3.MsgService",
    methods: [
      Sentinel_Session_V3_MsgServiceServerMetadata.Methods.msgCancelSession,
      Sentinel_Session_V3_MsgServiceServerMetadata.Methods.msgUpdateSession,
      Sentinel_Session_V3_MsgServiceServerMetadata.Methods.msgUpdateParams,
    ]
  )

  internal enum Methods {
    internal static let msgCancelSession = GRPCMethodDescriptor(
      name: "MsgCancelSession",
      path: "/sentinel.session.v3.MsgService/MsgCancelSession",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateSession = GRPCMethodDescriptor(
      name: "MsgUpdateSession",
      path: "/sentinel.session.v3.MsgService/MsgUpdateSession",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateParams = GRPCMethodDescriptor(
      name: "MsgUpdateParams",
      path: "/sentinel.session.v3.MsgService/MsgUpdateParams",
      type: GRPCCallType.unary
    )
  }
}
