//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/oracle/v1/querier.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Oracle_V1_QueryServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Oracle_V1_QueryServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func queryAssets(
    _ request: Sentinel_Oracle_V1_QueryAssetsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse>

  func queryAsset(
    _ request: Sentinel_Oracle_V1_QueryAssetRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse>

  func queryParams(
    _ request: Sentinel_Oracle_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse>
}

extension Sentinel_Oracle_V1_QueryServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.oracle.v1.QueryService"
  }

  /// Unary call to QueryAssets
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryAssets.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryAssets(
    _ request: Sentinel_Oracle_V1_QueryAssetsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAssets.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetsInterceptors() ?? []
    )
  }

  /// Unary call to QueryAsset
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryAsset.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryAsset(
    _ request: Sentinel_Oracle_V1_QueryAssetRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAsset.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetInterceptors() ?? []
    )
  }

  /// Unary call to QueryParams
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryParams(
    _ request: Sentinel_Oracle_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Oracle_V1_QueryServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Oracle_V1_QueryServiceNIOClient")
internal final class Sentinel_Oracle_V1_QueryServiceClient: Sentinel_Oracle_V1_QueryServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.oracle.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Oracle_V1_QueryServiceNIOClient: Sentinel_Oracle_V1_QueryServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.oracle.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Oracle_V1_QueryServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func makeQueryAssetsCall(
    _ request: Sentinel_Oracle_V1_QueryAssetsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse>

  func makeQueryAssetCall(
    _ request: Sentinel_Oracle_V1_QueryAssetRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse>

  func makeQueryParamsCall(
    _ request: Sentinel_Oracle_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Oracle_V1_QueryServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Oracle_V1_QueryServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeQueryAssetsCall(
    _ request: Sentinel_Oracle_V1_QueryAssetsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAssets.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetsInterceptors() ?? []
    )
  }

  internal func makeQueryAssetCall(
    _ request: Sentinel_Oracle_V1_QueryAssetRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAsset.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetInterceptors() ?? []
    )
  }

  internal func makeQueryParamsCall(
    _ request: Sentinel_Oracle_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Oracle_V1_QueryServiceAsyncClientProtocol {
  internal func queryAssets(
    _ request: Sentinel_Oracle_V1_QueryAssetsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Oracle_V1_QueryAssetsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAssets.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetsInterceptors() ?? []
    )
  }

  internal func queryAsset(
    _ request: Sentinel_Oracle_V1_QueryAssetRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Oracle_V1_QueryAssetResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAsset.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAssetInterceptors() ?? []
    )
  }

  internal func queryParams(
    _ request: Sentinel_Oracle_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Oracle_V1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Oracle_V1_QueryServiceAsyncClient: Sentinel_Oracle_V1_QueryServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Oracle_V1_QueryServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'queryAssets'.
  func makeQueryAssetsInterceptors() -> [ClientInterceptor<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse>]

  /// - Returns: Interceptors to use when invoking 'queryAsset'.
  func makeQueryAssetInterceptors() -> [ClientInterceptor<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse>]

  /// - Returns: Interceptors to use when invoking 'queryParams'.
  func makeQueryParamsInterceptors() -> [ClientInterceptor<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse>]
}

internal enum Sentinel_Oracle_V1_QueryServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "sentinel.oracle.v1.QueryService",
    methods: [
      Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAssets,
      Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryAsset,
      Sentinel_Oracle_V1_QueryServiceClientMetadata.Methods.queryParams,
    ]
  )

  internal enum Methods {
    internal static let queryAssets = GRPCMethodDescriptor(
      name: "QueryAssets",
      path: "/sentinel.oracle.v1.QueryService/QueryAssets",
      type: GRPCCallType.unary
    )

    internal static let queryAsset = GRPCMethodDescriptor(
      name: "QueryAsset",
      path: "/sentinel.oracle.v1.QueryService/QueryAsset",
      type: GRPCCallType.unary
    )

    internal static let queryParams = GRPCMethodDescriptor(
      name: "QueryParams",
      path: "/sentinel.oracle.v1.QueryService/QueryParams",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Oracle_V1_QueryServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Oracle_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  func queryAssets(request: Sentinel_Oracle_V1_QueryAssetsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Oracle_V1_QueryAssetsResponse>

  func queryAsset(request: Sentinel_Oracle_V1_QueryAssetRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Oracle_V1_QueryAssetResponse>

  func queryParams(request: Sentinel_Oracle_V1_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Oracle_V1_QueryParamsResponse>
}

extension Sentinel_Oracle_V1_QueryServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Oracle_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "QueryAssets":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryAssetsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryAssetsResponse>(),
        interceptors: self.interceptors?.makeQueryAssetsInterceptors() ?? [],
        userFunction: self.queryAssets(request:context:)
      )

    case "QueryAsset":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryAssetRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryAssetResponse>(),
        interceptors: self.interceptors?.makeQueryAssetInterceptors() ?? [],
        userFunction: self.queryAsset(request:context:)
      )

    case "QueryParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? [],
        userFunction: self.queryParams(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Oracle_V1_QueryServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Oracle_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  func queryAssets(
    request: Sentinel_Oracle_V1_QueryAssetsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Oracle_V1_QueryAssetsResponse

  func queryAsset(
    request: Sentinel_Oracle_V1_QueryAssetRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Oracle_V1_QueryAssetResponse

  func queryParams(
    request: Sentinel_Oracle_V1_QueryParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Oracle_V1_QueryParamsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Oracle_V1_QueryServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Oracle_V1_QueryServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Oracle_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Oracle_V1_QueryServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "QueryAssets":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryAssetsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryAssetsResponse>(),
        interceptors: self.interceptors?.makeQueryAssetsInterceptors() ?? [],
        wrapping: { try await self.queryAssets(request: $0, context: $1) }
      )

    case "QueryAsset":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryAssetRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryAssetResponse>(),
        interceptors: self.interceptors?.makeQueryAssetInterceptors() ?? [],
        wrapping: { try await self.queryAsset(request: $0, context: $1) }
      )

    case "QueryParams":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Oracle_V1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Oracle_V1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? [],
        wrapping: { try await self.queryParams(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Oracle_V1_QueryServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'queryAssets'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryAssetsInterceptors() -> [ServerInterceptor<Sentinel_Oracle_V1_QueryAssetsRequest, Sentinel_Oracle_V1_QueryAssetsResponse>]

  /// - Returns: Interceptors to use when handling 'queryAsset'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryAssetInterceptors() -> [ServerInterceptor<Sentinel_Oracle_V1_QueryAssetRequest, Sentinel_Oracle_V1_QueryAssetResponse>]

  /// - Returns: Interceptors to use when handling 'queryParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryParamsInterceptors() -> [ServerInterceptor<Sentinel_Oracle_V1_QueryParamsRequest, Sentinel_Oracle_V1_QueryParamsResponse>]
}

internal enum Sentinel_Oracle_V1_QueryServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "sentinel.oracle.v1.QueryService",
    methods: [
      Sentinel_Oracle_V1_QueryServiceServerMetadata.Methods.queryAssets,
      Sentinel_Oracle_V1_QueryServiceServerMetadata.Methods.queryAsset,
      Sentinel_Oracle_V1_QueryServiceServerMetadata.Methods.queryParams,
    ]
  )

  internal enum Methods {
    internal static let queryAssets = GRPCMethodDescriptor(
      name: "QueryAssets",
      path: "/sentinel.oracle.v1.QueryService/QueryAssets",
      type: GRPCCallType.unary
    )

    internal static let queryAsset = GRPCMethodDescriptor(
      name: "QueryAsset",
      path: "/sentinel.oracle.v1.QueryService/QueryAsset",
      type: GRPCCallType.unary
    )

    internal static let queryParams = GRPCMethodDescriptor(
      name: "QueryParams",
      path: "/sentinel.oracle.v1.QueryService/QueryParams",
      type: GRPCCallType.unary
    )
  }
}
