//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/subscription/v1/msg.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Subscription_V1_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Subscription_V1_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgAddQuota(
    _ request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse>

  func msgCancel(
    _ request: Sentinel_Subscription_V1_MsgCancelRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse>

  func msgSubscribeToNode(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>

  func msgSubscribeToPlan(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>

  func msgUpdateQuota(
    _ request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse>
}

extension Sentinel_Subscription_V1_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.subscription.v1.MsgService"
  }

  /// Unary call to MsgAddQuota
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgAddQuota.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgAddQuota(
    _ request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgAddQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddQuotaInterceptors() ?? []
    )
  }

  /// Unary call to MsgCancel
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgCancel.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgCancel(
    _ request: Sentinel_Subscription_V1_MsgCancelRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgCancel.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelInterceptors() ?? []
    )
  }

  /// Unary call to MsgSubscribeToNode
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgSubscribeToNode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgSubscribeToNode(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToNodeInterceptors() ?? []
    )
  }

  /// Unary call to MsgSubscribeToPlan
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgSubscribeToPlan.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgSubscribeToPlan(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToPlan.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToPlanInterceptors() ?? []
    )
  }

  /// Unary call to MsgUpdateQuota
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgUpdateQuota.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgUpdateQuota(
    _ request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgUpdateQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateQuotaInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Subscription_V1_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Subscription_V1_MsgServiceNIOClient")
internal final class Sentinel_Subscription_V1_MsgServiceClient: Sentinel_Subscription_V1_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.subscription.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Subscription_V1_MsgServiceNIOClient: Sentinel_Subscription_V1_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.subscription.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Subscription_V1_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgAddQuotaCall(
    _ request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse>

  func makeMsgCancelCall(
    _ request: Sentinel_Subscription_V1_MsgCancelRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse>

  func makeMsgSubscribeToNodeCall(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>

  func makeMsgSubscribeToPlanCall(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>

  func makeMsgUpdateQuotaCall(
    _ request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Subscription_V1_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Subscription_V1_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgAddQuotaCall(
    _ request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgAddQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddQuotaInterceptors() ?? []
    )
  }

  internal func makeMsgCancelCall(
    _ request: Sentinel_Subscription_V1_MsgCancelRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgCancel.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelInterceptors() ?? []
    )
  }

  internal func makeMsgSubscribeToNodeCall(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToNodeInterceptors() ?? []
    )
  }

  internal func makeMsgSubscribeToPlanCall(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToPlan.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToPlanInterceptors() ?? []
    )
  }

  internal func makeMsgUpdateQuotaCall(
    _ request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgUpdateQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateQuotaInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Subscription_V1_MsgServiceAsyncClientProtocol {
  internal func msgAddQuota(
    _ request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Subscription_V1_MsgAddQuotaResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgAddQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgAddQuotaInterceptors() ?? []
    )
  }

  internal func msgCancel(
    _ request: Sentinel_Subscription_V1_MsgCancelRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Subscription_V1_MsgCancelResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgCancel.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgCancelInterceptors() ?? []
    )
  }

  internal func msgSubscribeToNode(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Subscription_V1_MsgSubscribeToNodeResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToNode.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToNodeInterceptors() ?? []
    )
  }

  internal func msgSubscribeToPlan(
    _ request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Subscription_V1_MsgSubscribeToPlanResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToPlan.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSubscribeToPlanInterceptors() ?? []
    )
  }

  internal func msgUpdateQuota(
    _ request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Subscription_V1_MsgUpdateQuotaResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgUpdateQuota.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgUpdateQuotaInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Subscription_V1_MsgServiceAsyncClient: Sentinel_Subscription_V1_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Subscription_V1_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgAddQuota'.
  func makeMsgAddQuotaInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse>]

  /// - Returns: Interceptors to use when invoking 'msgCancel'.
  func makeMsgCancelInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse>]

  /// - Returns: Interceptors to use when invoking 'msgSubscribeToNode'.
  func makeMsgSubscribeToNodeInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>]

  /// - Returns: Interceptors to use when invoking 'msgSubscribeToPlan'.
  func makeMsgSubscribeToPlanInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>]

  /// - Returns: Interceptors to use when invoking 'msgUpdateQuota'.
  func makeMsgUpdateQuotaInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse>]
}

internal enum Sentinel_Subscription_V1_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.subscription.v1.MsgService",
    methods: [
      Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgAddQuota,
      Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgCancel,
      Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToNode,
      Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgSubscribeToPlan,
      Sentinel_Subscription_V1_MsgServiceClientMetadata.Methods.msgUpdateQuota,
    ]
  )

  internal enum Methods {
    internal static let msgAddQuota = GRPCMethodDescriptor(
      name: "MsgAddQuota",
      path: "/sentinel.subscription.v1.MsgService/MsgAddQuota",
      type: GRPCCallType.unary
    )

    internal static let msgCancel = GRPCMethodDescriptor(
      name: "MsgCancel",
      path: "/sentinel.subscription.v1.MsgService/MsgCancel",
      type: GRPCCallType.unary
    )

    internal static let msgSubscribeToNode = GRPCMethodDescriptor(
      name: "MsgSubscribeToNode",
      path: "/sentinel.subscription.v1.MsgService/MsgSubscribeToNode",
      type: GRPCCallType.unary
    )

    internal static let msgSubscribeToPlan = GRPCMethodDescriptor(
      name: "MsgSubscribeToPlan",
      path: "/sentinel.subscription.v1.MsgService/MsgSubscribeToPlan",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateQuota = GRPCMethodDescriptor(
      name: "MsgUpdateQuota",
      path: "/sentinel.subscription.v1.MsgService/MsgUpdateQuota",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Subscription_V1_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Subscription_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgAddQuota(request: Sentinel_Subscription_V1_MsgAddQuotaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V1_MsgAddQuotaResponse>

  func msgCancel(request: Sentinel_Subscription_V1_MsgCancelRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V1_MsgCancelResponse>

  func msgSubscribeToNode(request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>

  func msgSubscribeToPlan(request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>

  func msgUpdateQuota(request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V1_MsgUpdateQuotaResponse>
}

extension Sentinel_Subscription_V1_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Subscription_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgAddQuota":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgAddQuotaRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgAddQuotaResponse>(),
        interceptors: self.interceptors?.makeMsgAddQuotaInterceptors() ?? [],
        userFunction: self.msgAddQuota(request:context:)
      )

    case "MsgCancel":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgCancelRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgCancelResponse>(),
        interceptors: self.interceptors?.makeMsgCancelInterceptors() ?? [],
        userFunction: self.msgCancel(request:context:)
      )

    case "MsgSubscribeToNode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>(),
        interceptors: self.interceptors?.makeMsgSubscribeToNodeInterceptors() ?? [],
        userFunction: self.msgSubscribeToNode(request:context:)
      )

    case "MsgSubscribeToPlan":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>(),
        interceptors: self.interceptors?.makeMsgSubscribeToPlanInterceptors() ?? [],
        userFunction: self.msgSubscribeToPlan(request:context:)
      )

    case "MsgUpdateQuota":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgUpdateQuotaRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgUpdateQuotaResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateQuotaInterceptors() ?? [],
        userFunction: self.msgUpdateQuota(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Subscription_V1_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Subscription_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgAddQuota(
    request: Sentinel_Subscription_V1_MsgAddQuotaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Subscription_V1_MsgAddQuotaResponse

  func msgCancel(
    request: Sentinel_Subscription_V1_MsgCancelRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Subscription_V1_MsgCancelResponse

  func msgSubscribeToNode(
    request: Sentinel_Subscription_V1_MsgSubscribeToNodeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Subscription_V1_MsgSubscribeToNodeResponse

  func msgSubscribeToPlan(
    request: Sentinel_Subscription_V1_MsgSubscribeToPlanRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Subscription_V1_MsgSubscribeToPlanResponse

  func msgUpdateQuota(
    request: Sentinel_Subscription_V1_MsgUpdateQuotaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Subscription_V1_MsgUpdateQuotaResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Subscription_V1_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Subscription_V1_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Subscription_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Subscription_V1_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgAddQuota":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgAddQuotaRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgAddQuotaResponse>(),
        interceptors: self.interceptors?.makeMsgAddQuotaInterceptors() ?? [],
        wrapping: { try await self.msgAddQuota(request: $0, context: $1) }
      )

    case "MsgCancel":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgCancelRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgCancelResponse>(),
        interceptors: self.interceptors?.makeMsgCancelInterceptors() ?? [],
        wrapping: { try await self.msgCancel(request: $0, context: $1) }
      )

    case "MsgSubscribeToNode":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>(),
        interceptors: self.interceptors?.makeMsgSubscribeToNodeInterceptors() ?? [],
        wrapping: { try await self.msgSubscribeToNode(request: $0, context: $1) }
      )

    case "MsgSubscribeToPlan":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>(),
        interceptors: self.interceptors?.makeMsgSubscribeToPlanInterceptors() ?? [],
        wrapping: { try await self.msgSubscribeToPlan(request: $0, context: $1) }
      )

    case "MsgUpdateQuota":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V1_MsgUpdateQuotaRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V1_MsgUpdateQuotaResponse>(),
        interceptors: self.interceptors?.makeMsgUpdateQuotaInterceptors() ?? [],
        wrapping: { try await self.msgUpdateQuota(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Subscription_V1_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgAddQuota'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgAddQuotaInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V1_MsgAddQuotaRequest, Sentinel_Subscription_V1_MsgAddQuotaResponse>]

  /// - Returns: Interceptors to use when handling 'msgCancel'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgCancelInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V1_MsgCancelRequest, Sentinel_Subscription_V1_MsgCancelResponse>]

  /// - Returns: Interceptors to use when handling 'msgSubscribeToNode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgSubscribeToNodeInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V1_MsgSubscribeToNodeRequest, Sentinel_Subscription_V1_MsgSubscribeToNodeResponse>]

  /// - Returns: Interceptors to use when handling 'msgSubscribeToPlan'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgSubscribeToPlanInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V1_MsgSubscribeToPlanRequest, Sentinel_Subscription_V1_MsgSubscribeToPlanResponse>]

  /// - Returns: Interceptors to use when handling 'msgUpdateQuota'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgUpdateQuotaInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V1_MsgUpdateQuotaRequest, Sentinel_Subscription_V1_MsgUpdateQuotaResponse>]
}

internal enum Sentinel_Subscription_V1_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.subscription.v1.MsgService",
    methods: [
      Sentinel_Subscription_V1_MsgServiceServerMetadata.Methods.msgAddQuota,
      Sentinel_Subscription_V1_MsgServiceServerMetadata.Methods.msgCancel,
      Sentinel_Subscription_V1_MsgServiceServerMetadata.Methods.msgSubscribeToNode,
      Sentinel_Subscription_V1_MsgServiceServerMetadata.Methods.msgSubscribeToPlan,
      Sentinel_Subscription_V1_MsgServiceServerMetadata.Methods.msgUpdateQuota,
    ]
  )

  internal enum Methods {
    internal static let msgAddQuota = GRPCMethodDescriptor(
      name: "MsgAddQuota",
      path: "/sentinel.subscription.v1.MsgService/MsgAddQuota",
      type: GRPCCallType.unary
    )

    internal static let msgCancel = GRPCMethodDescriptor(
      name: "MsgCancel",
      path: "/sentinel.subscription.v1.MsgService/MsgCancel",
      type: GRPCCallType.unary
    )

    internal static let msgSubscribeToNode = GRPCMethodDescriptor(
      name: "MsgSubscribeToNode",
      path: "/sentinel.subscription.v1.MsgService/MsgSubscribeToNode",
      type: GRPCCallType.unary
    )

    internal static let msgSubscribeToPlan = GRPCMethodDescriptor(
      name: "MsgSubscribeToPlan",
      path: "/sentinel.subscription.v1.MsgService/MsgSubscribeToPlan",
      type: GRPCCallType.unary
    )

    internal static let msgUpdateQuota = GRPCMethodDescriptor(
      name: "MsgUpdateQuota",
      path: "/sentinel.subscription.v1.MsgService/MsgUpdateQuota",
      type: GRPCCallType.unary
    )
  }
}
