//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/swap/v1/msg.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Swap_V1_MsgServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Swap_V1_MsgServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func msgSwap(
    _ request: Sentinel_Swap_V1_MsgSwapRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse>
}

extension Sentinel_Swap_V1_MsgServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.swap.v1.MsgService"
  }

  /// Unary call to MsgSwap
  ///
  /// - Parameters:
  ///   - request: Request to send to MsgSwap.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func msgSwap(
    _ request: Sentinel_Swap_V1_MsgSwapRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Swap_V1_MsgServiceClientMetadata.Methods.msgSwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSwapInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Swap_V1_MsgServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Swap_V1_MsgServiceNIOClient")
internal final class Sentinel_Swap_V1_MsgServiceClient: Sentinel_Swap_V1_MsgServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.swap.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Swap_V1_MsgServiceNIOClient: Sentinel_Swap_V1_MsgServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.swap.v1.MsgService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Swap_V1_MsgServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? { get }

  func makeMsgSwapCall(
    _ request: Sentinel_Swap_V1_MsgSwapRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_MsgServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Swap_V1_MsgServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeMsgSwapCall(
    _ request: Sentinel_Swap_V1_MsgSwapRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Swap_V1_MsgServiceClientMetadata.Methods.msgSwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSwapInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_MsgServiceAsyncClientProtocol {
  internal func msgSwap(
    _ request: Sentinel_Swap_V1_MsgSwapRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Swap_V1_MsgSwapResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Swap_V1_MsgServiceClientMetadata.Methods.msgSwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMsgSwapInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Swap_V1_MsgServiceAsyncClient: Sentinel_Swap_V1_MsgServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Swap_V1_MsgServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'msgSwap'.
  func makeMsgSwapInterceptors() -> [ClientInterceptor<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse>]
}

internal enum Sentinel_Swap_V1_MsgServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.swap.v1.MsgService",
    methods: [
      Sentinel_Swap_V1_MsgServiceClientMetadata.Methods.msgSwap,
    ]
  )

  internal enum Methods {
    internal static let msgSwap = GRPCMethodDescriptor(
      name: "MsgSwap",
      path: "/sentinel.swap.v1.MsgService/MsgSwap",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Swap_V1_MsgServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Swap_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgSwap(request: Sentinel_Swap_V1_MsgSwapRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Swap_V1_MsgSwapResponse>
}

extension Sentinel_Swap_V1_MsgServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Swap_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgSwap":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_MsgSwapRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_MsgSwapResponse>(),
        interceptors: self.interceptors?.makeMsgSwapInterceptors() ?? [],
        userFunction: self.msgSwap(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Swap_V1_MsgServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Swap_V1_MsgServiceServerInterceptorFactoryProtocol? { get }

  func msgSwap(
    request: Sentinel_Swap_V1_MsgSwapRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Swap_V1_MsgSwapResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_MsgServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Swap_V1_MsgServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Swap_V1_MsgServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Swap_V1_MsgServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "MsgSwap":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_MsgSwapRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_MsgSwapResponse>(),
        interceptors: self.interceptors?.makeMsgSwapInterceptors() ?? [],
        wrapping: { try await self.msgSwap(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Swap_V1_MsgServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'msgSwap'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMsgSwapInterceptors() -> [ServerInterceptor<Sentinel_Swap_V1_MsgSwapRequest, Sentinel_Swap_V1_MsgSwapResponse>]
}

internal enum Sentinel_Swap_V1_MsgServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MsgService",
    fullName: "sentinel.swap.v1.MsgService",
    methods: [
      Sentinel_Swap_V1_MsgServiceServerMetadata.Methods.msgSwap,
    ]
  )

  internal enum Methods {
    internal static let msgSwap = GRPCMethodDescriptor(
      name: "MsgSwap",
      path: "/sentinel.swap.v1.MsgService/MsgSwap",
      type: GRPCCallType.unary
    )
  }
}
