//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sentinel/swap/v1/querier.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Swap_V1_QueryServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Swap_V1_QueryServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func querySwaps(
    _ request: Sentinel_Swap_V1_QuerySwapsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse>

  func querySwap(
    _ request: Sentinel_Swap_V1_QuerySwapRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse>

  func queryParams(
    _ request: Sentinel_Swap_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse>
}

extension Sentinel_Swap_V1_QueryServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.swap.v1.QueryService"
  }

  /// Unary call to QuerySwaps
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySwaps.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySwaps(
    _ request: Sentinel_Swap_V1_QuerySwapsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwaps.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapsInterceptors() ?? []
    )
  }

  /// Unary call to QuerySwap
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySwap.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySwap(
    _ request: Sentinel_Swap_V1_QuerySwapRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapInterceptors() ?? []
    )
  }

  /// Unary call to QueryParams
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryParams(
    _ request: Sentinel_Swap_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sentinel_Swap_V1_QueryServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sentinel_Swap_V1_QueryServiceNIOClient")
internal final class Sentinel_Swap_V1_QueryServiceClient: Sentinel_Swap_V1_QueryServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sentinel.swap.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sentinel_Swap_V1_QueryServiceNIOClient: Sentinel_Swap_V1_QueryServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.swap.v1.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Swap_V1_QueryServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? { get }

  func makeQuerySwapsCall(
    _ request: Sentinel_Swap_V1_QuerySwapsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse>

  func makeQuerySwapCall(
    _ request: Sentinel_Swap_V1_QuerySwapRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse>

  func makeQueryParamsCall(
    _ request: Sentinel_Swap_V1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_QueryServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Swap_V1_QueryServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeQuerySwapsCall(
    _ request: Sentinel_Swap_V1_QuerySwapsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwaps.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapsInterceptors() ?? []
    )
  }

  internal func makeQuerySwapCall(
    _ request: Sentinel_Swap_V1_QuerySwapRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapInterceptors() ?? []
    )
  }

  internal func makeQueryParamsCall(
    _ request: Sentinel_Swap_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_QueryServiceAsyncClientProtocol {
  internal func querySwaps(
    _ request: Sentinel_Swap_V1_QuerySwapsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Swap_V1_QuerySwapsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwaps.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapsInterceptors() ?? []
    )
  }

  internal func querySwap(
    _ request: Sentinel_Swap_V1_QuerySwapRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Swap_V1_QuerySwapResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySwapInterceptors() ?? []
    )
  }

  internal func queryParams(
    _ request: Sentinel_Swap_V1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sentinel_Swap_V1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.queryParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sentinel_Swap_V1_QueryServiceAsyncClient: Sentinel_Swap_V1_QueryServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sentinel_Swap_V1_QueryServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'querySwaps'.
  func makeQuerySwapsInterceptors() -> [ClientInterceptor<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse>]

  /// - Returns: Interceptors to use when invoking 'querySwap'.
  func makeQuerySwapInterceptors() -> [ClientInterceptor<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse>]

  /// - Returns: Interceptors to use when invoking 'queryParams'.
  func makeQueryParamsInterceptors() -> [ClientInterceptor<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse>]
}

internal enum Sentinel_Swap_V1_QueryServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "sentinel.swap.v1.QueryService",
    methods: [
      Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwaps,
      Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.querySwap,
      Sentinel_Swap_V1_QueryServiceClientMetadata.Methods.queryParams,
    ]
  )

  internal enum Methods {
    internal static let querySwaps = GRPCMethodDescriptor(
      name: "QuerySwaps",
      path: "/sentinel.swap.v1.QueryService/QuerySwaps",
      type: GRPCCallType.unary
    )

    internal static let querySwap = GRPCMethodDescriptor(
      name: "QuerySwap",
      path: "/sentinel.swap.v1.QueryService/QuerySwap",
      type: GRPCCallType.unary
    )

    internal static let queryParams = GRPCMethodDescriptor(
      name: "QueryParams",
      path: "/sentinel.swap.v1.QueryService/QueryParams",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Swap_V1_QueryServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Swap_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  func querySwaps(request: Sentinel_Swap_V1_QuerySwapsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Swap_V1_QuerySwapsResponse>

  func querySwap(request: Sentinel_Swap_V1_QuerySwapRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Swap_V1_QuerySwapResponse>

  func queryParams(request: Sentinel_Swap_V1_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Swap_V1_QueryParamsResponse>
}

extension Sentinel_Swap_V1_QueryServiceProvider {
  internal var serviceName: Substring {
    return Sentinel_Swap_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "QuerySwaps":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QuerySwapsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QuerySwapsResponse>(),
        interceptors: self.interceptors?.makeQuerySwapsInterceptors() ?? [],
        userFunction: self.querySwaps(request:context:)
      )

    case "QuerySwap":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QuerySwapRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QuerySwapResponse>(),
        interceptors: self.interceptors?.makeQuerySwapInterceptors() ?? [],
        userFunction: self.querySwap(request:context:)
      )

    case "QueryParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? [],
        userFunction: self.queryParams(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sentinel_Swap_V1_QueryServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sentinel_Swap_V1_QueryServiceServerInterceptorFactoryProtocol? { get }

  func querySwaps(
    request: Sentinel_Swap_V1_QuerySwapsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Swap_V1_QuerySwapsResponse

  func querySwap(
    request: Sentinel_Swap_V1_QuerySwapRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Swap_V1_QuerySwapResponse

  func queryParams(
    request: Sentinel_Swap_V1_QueryParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sentinel_Swap_V1_QueryParamsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sentinel_Swap_V1_QueryServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sentinel_Swap_V1_QueryServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sentinel_Swap_V1_QueryServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sentinel_Swap_V1_QueryServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "QuerySwaps":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QuerySwapsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QuerySwapsResponse>(),
        interceptors: self.interceptors?.makeQuerySwapsInterceptors() ?? [],
        wrapping: { try await self.querySwaps(request: $0, context: $1) }
      )

    case "QuerySwap":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QuerySwapRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QuerySwapResponse>(),
        interceptors: self.interceptors?.makeQuerySwapInterceptors() ?? [],
        wrapping: { try await self.querySwap(request: $0, context: $1) }
      )

    case "QueryParams":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Swap_V1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Swap_V1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? [],
        wrapping: { try await self.queryParams(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Swap_V1_QueryServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'querySwaps'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySwapsInterceptors() -> [ServerInterceptor<Sentinel_Swap_V1_QuerySwapsRequest, Sentinel_Swap_V1_QuerySwapsResponse>]

  /// - Returns: Interceptors to use when handling 'querySwap'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySwapInterceptors() -> [ServerInterceptor<Sentinel_Swap_V1_QuerySwapRequest, Sentinel_Swap_V1_QuerySwapResponse>]

  /// - Returns: Interceptors to use when handling 'queryParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryParamsInterceptors() -> [ServerInterceptor<Sentinel_Swap_V1_QueryParamsRequest, Sentinel_Swap_V1_QueryParamsResponse>]
}

internal enum Sentinel_Swap_V1_QueryServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QueryService",
    fullName: "sentinel.swap.v1.QueryService",
    methods: [
      Sentinel_Swap_V1_QueryServiceServerMetadata.Methods.querySwaps,
      Sentinel_Swap_V1_QueryServiceServerMetadata.Methods.querySwap,
      Sentinel_Swap_V1_QueryServiceServerMetadata.Methods.queryParams,
    ]
  )

  internal enum Methods {
    internal static let querySwaps = GRPCMethodDescriptor(
      name: "QuerySwaps",
      path: "/sentinel.swap.v1.QueryService/QuerySwaps",
      type: GRPCCallType.unary
    )

    internal static let querySwap = GRPCMethodDescriptor(
      name: "QuerySwap",
      path: "/sentinel.swap.v1.QueryService/QuerySwap",
      type: GRPCCallType.unary
    )

    internal static let queryParams = GRPCMethodDescriptor(
      name: "QueryParams",
      path: "/sentinel.swap.v1.QueryService/QueryParams",
      type: GRPCCallType.unary
    )
  }
}
