//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: sentinel/subscription/v2/querier.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Sentinel_Subscription_V2_QueryServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sentinel_Subscription_V2_QueryServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sentinel_Subscription_V2_QueryServiceClientInterceptorFactoryProtocol? { get }

  func querySubscriptions(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsRequest, Sentinel_Subscription_V2_QuerySubscriptionsResponse>

  func querySubscriptionsForAccount(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest, Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse>

  func querySubscriptionsForNode(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest, Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse>

  func querySubscriptionsForPlan(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest, Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse>

  func querySubscription(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionRequest, Sentinel_Subscription_V2_QuerySubscriptionResponse>

  func queryAllocations(
    _ request: Sentinel_Subscription_V2_QueryAllocationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryAllocationsRequest, Sentinel_Subscription_V2_QueryAllocationsResponse>

  func queryAllocation(
    _ request: Sentinel_Subscription_V2_QueryAllocationRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryAllocationRequest, Sentinel_Subscription_V2_QueryAllocationResponse>

  func queryPayouts(
    _ request: Sentinel_Subscription_V2_QueryPayoutsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsRequest, Sentinel_Subscription_V2_QueryPayoutsResponse>

  func queryPayoutsForAccount(
    _ request: Sentinel_Subscription_V2_QueryPayoutsForAccountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsForAccountRequest, Sentinel_Subscription_V2_QueryPayoutsForAccountResponse>

  func queryPayoutsForNode(
    _ request: Sentinel_Subscription_V2_QueryPayoutsForNodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsForNodeRequest, Sentinel_Subscription_V2_QueryPayoutsForNodeResponse>

  func queryPayout(
    _ request: Sentinel_Subscription_V2_QueryPayoutRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutRequest, Sentinel_Subscription_V2_QueryPayoutResponse>

  func queryParams(
    _ request: Sentinel_Subscription_V2_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryParamsRequest, Sentinel_Subscription_V2_QueryParamsResponse>
}

extension Sentinel_Subscription_V2_QueryServiceClientProtocol {
  internal var serviceName: String {
    return "sentinel.subscription.v2.QueryService"
  }

  /// Unary call to QuerySubscriptions
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySubscriptions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySubscriptions(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsRequest, Sentinel_Subscription_V2_QuerySubscriptionsResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QuerySubscriptions",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySubscriptionsInterceptors() ?? []
    )
  }

  /// Unary call to QuerySubscriptionsForAccount
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySubscriptionsForAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySubscriptionsForAccount(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest, Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QuerySubscriptionsForAccount",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySubscriptionsForAccountInterceptors() ?? []
    )
  }

  /// Unary call to QuerySubscriptionsForNode
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySubscriptionsForNode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySubscriptionsForNode(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest, Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QuerySubscriptionsForNode",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySubscriptionsForNodeInterceptors() ?? []
    )
  }

  /// Unary call to QuerySubscriptionsForPlan
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySubscriptionsForPlan.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySubscriptionsForPlan(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest, Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QuerySubscriptionsForPlan",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySubscriptionsForPlanInterceptors() ?? []
    )
  }

  /// Unary call to QuerySubscription
  ///
  /// - Parameters:
  ///   - request: Request to send to QuerySubscription.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func querySubscription(
    _ request: Sentinel_Subscription_V2_QuerySubscriptionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QuerySubscriptionRequest, Sentinel_Subscription_V2_QuerySubscriptionResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QuerySubscription",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuerySubscriptionInterceptors() ?? []
    )
  }

  /// Unary call to QueryAllocations
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryAllocations.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryAllocations(
    _ request: Sentinel_Subscription_V2_QueryAllocationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryAllocationsRequest, Sentinel_Subscription_V2_QueryAllocationsResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryAllocations",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAllocationsInterceptors() ?? []
    )
  }

  /// Unary call to QueryAllocation
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryAllocation.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryAllocation(
    _ request: Sentinel_Subscription_V2_QueryAllocationRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryAllocationRequest, Sentinel_Subscription_V2_QueryAllocationResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryAllocation",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryAllocationInterceptors() ?? []
    )
  }

  /// Unary call to QueryPayouts
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryPayouts.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryPayouts(
    _ request: Sentinel_Subscription_V2_QueryPayoutsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsRequest, Sentinel_Subscription_V2_QueryPayoutsResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryPayouts",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryPayoutsInterceptors() ?? []
    )
  }

  /// Unary call to QueryPayoutsForAccount
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryPayoutsForAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryPayoutsForAccount(
    _ request: Sentinel_Subscription_V2_QueryPayoutsForAccountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsForAccountRequest, Sentinel_Subscription_V2_QueryPayoutsForAccountResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryPayoutsForAccount",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryPayoutsForAccountInterceptors() ?? []
    )
  }

  /// Unary call to QueryPayoutsForNode
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryPayoutsForNode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryPayoutsForNode(
    _ request: Sentinel_Subscription_V2_QueryPayoutsForNodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutsForNodeRequest, Sentinel_Subscription_V2_QueryPayoutsForNodeResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryPayoutsForNode",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryPayoutsForNodeInterceptors() ?? []
    )
  }

  /// Unary call to QueryPayout
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryPayout.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryPayout(
    _ request: Sentinel_Subscription_V2_QueryPayoutRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryPayoutRequest, Sentinel_Subscription_V2_QueryPayoutResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryPayout",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryPayoutInterceptors() ?? []
    )
  }

  /// Unary call to QueryParams
  ///
  /// - Parameters:
  ///   - request: Request to send to QueryParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queryParams(
    _ request: Sentinel_Subscription_V2_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sentinel_Subscription_V2_QueryParamsRequest, Sentinel_Subscription_V2_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: "/sentinel.subscription.v2.QueryService/QueryParams",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? []
    )
  }
}

internal protocol Sentinel_Subscription_V2_QueryServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'querySubscriptions'.
  func makeQuerySubscriptionsInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsRequest, Sentinel_Subscription_V2_QuerySubscriptionsResponse>]

  /// - Returns: Interceptors to use when invoking 'querySubscriptionsForAccount'.
  func makeQuerySubscriptionsForAccountInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest, Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse>]

  /// - Returns: Interceptors to use when invoking 'querySubscriptionsForNode'.
  func makeQuerySubscriptionsForNodeInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest, Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse>]

  /// - Returns: Interceptors to use when invoking 'querySubscriptionsForPlan'.
  func makeQuerySubscriptionsForPlanInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest, Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse>]

  /// - Returns: Interceptors to use when invoking 'querySubscription'.
  func makeQuerySubscriptionInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QuerySubscriptionRequest, Sentinel_Subscription_V2_QuerySubscriptionResponse>]

  /// - Returns: Interceptors to use when invoking 'queryAllocations'.
  func makeQueryAllocationsInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryAllocationsRequest, Sentinel_Subscription_V2_QueryAllocationsResponse>]

  /// - Returns: Interceptors to use when invoking 'queryAllocation'.
  func makeQueryAllocationInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryAllocationRequest, Sentinel_Subscription_V2_QueryAllocationResponse>]

  /// - Returns: Interceptors to use when invoking 'queryPayouts'.
  func makeQueryPayoutsInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryPayoutsRequest, Sentinel_Subscription_V2_QueryPayoutsResponse>]

  /// - Returns: Interceptors to use when invoking 'queryPayoutsForAccount'.
  func makeQueryPayoutsForAccountInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryPayoutsForAccountRequest, Sentinel_Subscription_V2_QueryPayoutsForAccountResponse>]

  /// - Returns: Interceptors to use when invoking 'queryPayoutsForNode'.
  func makeQueryPayoutsForNodeInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryPayoutsForNodeRequest, Sentinel_Subscription_V2_QueryPayoutsForNodeResponse>]

  /// - Returns: Interceptors to use when invoking 'queryPayout'.
  func makeQueryPayoutInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryPayoutRequest, Sentinel_Subscription_V2_QueryPayoutResponse>]

  /// - Returns: Interceptors to use when invoking 'queryParams'.
  func makeQueryParamsInterceptors() -> [ClientInterceptor<Sentinel_Subscription_V2_QueryParamsRequest, Sentinel_Subscription_V2_QueryParamsResponse>]
}

internal final class Sentinel_Subscription_V2_QueryServiceClient: Sentinel_Subscription_V2_QueryServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sentinel_Subscription_V2_QueryServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sentinel.subscription.v2.QueryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sentinel_Subscription_V2_QueryServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sentinel_Subscription_V2_QueryServiceProvider: CallHandlerProvider {
  var interceptors: Sentinel_Subscription_V2_QueryServiceServerInterceptorFactoryProtocol? { get }

  func querySubscriptions(request: Sentinel_Subscription_V2_QuerySubscriptionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QuerySubscriptionsResponse>

  func querySubscriptionsForAccount(request: Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse>

  func querySubscriptionsForNode(request: Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse>

  func querySubscriptionsForPlan(request: Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse>

  func querySubscription(request: Sentinel_Subscription_V2_QuerySubscriptionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QuerySubscriptionResponse>

  func queryAllocations(request: Sentinel_Subscription_V2_QueryAllocationsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryAllocationsResponse>

  func queryAllocation(request: Sentinel_Subscription_V2_QueryAllocationRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryAllocationResponse>

  func queryPayouts(request: Sentinel_Subscription_V2_QueryPayoutsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryPayoutsResponse>

  func queryPayoutsForAccount(request: Sentinel_Subscription_V2_QueryPayoutsForAccountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryPayoutsForAccountResponse>

  func queryPayoutsForNode(request: Sentinel_Subscription_V2_QueryPayoutsForNodeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryPayoutsForNodeResponse>

  func queryPayout(request: Sentinel_Subscription_V2_QueryPayoutRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryPayoutResponse>

  func queryParams(request: Sentinel_Subscription_V2_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sentinel_Subscription_V2_QueryParamsResponse>
}

extension Sentinel_Subscription_V2_QueryServiceProvider {
  internal var serviceName: Substring { return "sentinel.subscription.v2.QueryService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "QuerySubscriptions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QuerySubscriptionsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QuerySubscriptionsResponse>(),
        interceptors: self.interceptors?.makeQuerySubscriptionsInterceptors() ?? [],
        userFunction: self.querySubscriptions(request:context:)
      )

    case "QuerySubscriptionsForAccount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse>(),
        interceptors: self.interceptors?.makeQuerySubscriptionsForAccountInterceptors() ?? [],
        userFunction: self.querySubscriptionsForAccount(request:context:)
      )

    case "QuerySubscriptionsForNode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse>(),
        interceptors: self.interceptors?.makeQuerySubscriptionsForNodeInterceptors() ?? [],
        userFunction: self.querySubscriptionsForNode(request:context:)
      )

    case "QuerySubscriptionsForPlan":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse>(),
        interceptors: self.interceptors?.makeQuerySubscriptionsForPlanInterceptors() ?? [],
        userFunction: self.querySubscriptionsForPlan(request:context:)
      )

    case "QuerySubscription":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QuerySubscriptionRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QuerySubscriptionResponse>(),
        interceptors: self.interceptors?.makeQuerySubscriptionInterceptors() ?? [],
        userFunction: self.querySubscription(request:context:)
      )

    case "QueryAllocations":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryAllocationsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryAllocationsResponse>(),
        interceptors: self.interceptors?.makeQueryAllocationsInterceptors() ?? [],
        userFunction: self.queryAllocations(request:context:)
      )

    case "QueryAllocation":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryAllocationRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryAllocationResponse>(),
        interceptors: self.interceptors?.makeQueryAllocationInterceptors() ?? [],
        userFunction: self.queryAllocation(request:context:)
      )

    case "QueryPayouts":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryPayoutsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryPayoutsResponse>(),
        interceptors: self.interceptors?.makeQueryPayoutsInterceptors() ?? [],
        userFunction: self.queryPayouts(request:context:)
      )

    case "QueryPayoutsForAccount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryPayoutsForAccountRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryPayoutsForAccountResponse>(),
        interceptors: self.interceptors?.makeQueryPayoutsForAccountInterceptors() ?? [],
        userFunction: self.queryPayoutsForAccount(request:context:)
      )

    case "QueryPayoutsForNode":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryPayoutsForNodeRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryPayoutsForNodeResponse>(),
        interceptors: self.interceptors?.makeQueryPayoutsForNodeInterceptors() ?? [],
        userFunction: self.queryPayoutsForNode(request:context:)
      )

    case "QueryPayout":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryPayoutRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryPayoutResponse>(),
        interceptors: self.interceptors?.makeQueryPayoutInterceptors() ?? [],
        userFunction: self.queryPayout(request:context:)
      )

    case "QueryParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sentinel_Subscription_V2_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Sentinel_Subscription_V2_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeQueryParamsInterceptors() ?? [],
        userFunction: self.queryParams(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Sentinel_Subscription_V2_QueryServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'querySubscriptions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySubscriptionsInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsRequest, Sentinel_Subscription_V2_QuerySubscriptionsResponse>]

  /// - Returns: Interceptors to use when handling 'querySubscriptionsForAccount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySubscriptionsForAccountInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForAccountRequest, Sentinel_Subscription_V2_QuerySubscriptionsForAccountResponse>]

  /// - Returns: Interceptors to use when handling 'querySubscriptionsForNode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySubscriptionsForNodeInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForNodeRequest, Sentinel_Subscription_V2_QuerySubscriptionsForNodeResponse>]

  /// - Returns: Interceptors to use when handling 'querySubscriptionsForPlan'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySubscriptionsForPlanInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QuerySubscriptionsForPlanRequest, Sentinel_Subscription_V2_QuerySubscriptionsForPlanResponse>]

  /// - Returns: Interceptors to use when handling 'querySubscription'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQuerySubscriptionInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QuerySubscriptionRequest, Sentinel_Subscription_V2_QuerySubscriptionResponse>]

  /// - Returns: Interceptors to use when handling 'queryAllocations'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryAllocationsInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryAllocationsRequest, Sentinel_Subscription_V2_QueryAllocationsResponse>]

  /// - Returns: Interceptors to use when handling 'queryAllocation'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryAllocationInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryAllocationRequest, Sentinel_Subscription_V2_QueryAllocationResponse>]

  /// - Returns: Interceptors to use when handling 'queryPayouts'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryPayoutsInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryPayoutsRequest, Sentinel_Subscription_V2_QueryPayoutsResponse>]

  /// - Returns: Interceptors to use when handling 'queryPayoutsForAccount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryPayoutsForAccountInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryPayoutsForAccountRequest, Sentinel_Subscription_V2_QueryPayoutsForAccountResponse>]

  /// - Returns: Interceptors to use when handling 'queryPayoutsForNode'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryPayoutsForNodeInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryPayoutsForNodeRequest, Sentinel_Subscription_V2_QueryPayoutsForNodeResponse>]

  /// - Returns: Interceptors to use when handling 'queryPayout'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryPayoutInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryPayoutRequest, Sentinel_Subscription_V2_QueryPayoutResponse>]

  /// - Returns: Interceptors to use when handling 'queryParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueryParamsInterceptors() -> [ServerInterceptor<Sentinel_Subscription_V2_QueryParamsRequest, Sentinel_Subscription_V2_QueryParamsResponse>]
}
